### ISSUE TITLE
Update to Heltec CubeCell (ASR650X) Arduino Support V1.7.1

### ISSUE THREAD

**Issue by jezdd** [HelTecAutomation/platform-heltec-cubecell#9]
Please can we promote PatformIO to [Heltec CubeCell (ASR650X) Arduino Support V1.7.1 release

**Comment by eikaramba** [comment]
yes please why is the platform io so outdated? any way to manually maybe patch it locally?

**Comment by eikaramba** [comment]
tried this:
```
[env:cubecell_board]
platform = https://github.com/HelTecAutomation/heltec-cubecell.git
board = cubecell_board_v2
framework = arduino
upload_port = COM4
monitor_speed = 115200
board_build.arduino.lorawan.region = EU868
board_build.arduino.lorawan.debug_level = NONE # NONE | FREQ_AND_DIO
board_build.arduino.lorawan.rgb = ACTIVE  #default ACTIVE if DEACTIVE somehow i get noisy switch interrupts
board_build.arduino.lorawan.at_support = OFF #default ON
board_build.arduino.lorawan.net_reserve = OFF #default OFF
board_build.arduino.lorawan.adr = ON #default ON
board_build.arduino.lorawan.class = CLASS_A #default CLASS_A
board_build.arduino.lorawan.uplinkmode = CONFIRMED #default CONFIRMED
board_build.arduino.lorawan.preamble_length = 8 #default 8
monitor_filters = send_on_enter
monitor_echo = yes
platform_packages =
  framework-arduinocubecell@https://github.com/HelTecAutomation/CubeCell-Arduino.git#V1.7.1
```

**but that gives me the following on build:**

Archiving .pio\build\cubecell_board\lib3a8\libLoraWan102.a
Compiling .pio\build\cubecell_board\FrameworkArduino\cores\I2C_I2C.c.o
In file included from C:\Users\eike\.platformio\packages\framework-arduinocubecell\libraries\DISPLAY\src\HT_st7735.cpp:3:
C:\Users\eike\.platformio\packages\framework-arduinocubecell\libraries\DISPLAY\src\HT_st7735.h:21:30: error: 'GPIO8' was not declared in this scope; did you mean 'GPIO0'?
   21 | #define ST7735_DC_Pin        GPIO8
      |                              ^~~~~
C:\Users\eike\.platformio\packages\framework-arduinocubecell\libraries\DISPLAY\src\HT_st7735.h:271:22: note: in expansion of macro 'ST7735_DC_Pin'
  271 |     int8_t    dc_pin=ST7735_DC_Pin,
      |                      ^~~~~~~~~~~~~
C:\Users\eike\.platformio\packages\framework-arduinocubecell\libraries\DISPLAY\src\HT_st7735.cpp: In member function 'void HT_st7735::st7735_fill_rectangle(uint16_t, uint16_t, uint16_t, uint16_t, uint16_t)':
C:\Users\eike\.platformio\packages\framework-arduinocubecell\libraries\DISPLAY\src\HT_st7735.h:21:30: error: 'GPIO8' was not declared in this scope; did you mean 'GPIO0'?
   21 | #define ST7735_DC_Pin        GPIO8
      |                              ^~~~~
C:\Users\eike\.platformio\packages\framework-arduinocubecell\libraries\DISPLAY\src\HT_st7735.cpp:283:18: note: in expansion of macro 'ST7735_DC_Pin'
  283 |     digitalWrite(ST7735_DC_Pin, HIGH);
      |                  ^~~~~~~~~~~~~
*** [.pio\build\cubecell_board\libac8\DISPLAY\HT_st7735.cpp.o] Error 1
Indexing .pio\build\cubecell_board\libFrameworkArduinoVariant.a

**Comment by jezdd** [comment]
Got it working with 1.7.0 >>

platform_packages = framework-arduinocubecell@https://github.com/HelTecAutomation/CubeCell-Arduino@1.7.0

I could not get a compile from 1.7.1 as it has some older version tags in it that PatformIO flags up.

**Comment by eikaramba** [comment]
intersting with
platform_packages = framework-arduinocubecell@https://github.com/HelTecAutomation/CubeCell-Arduino@1.7.0
i get
fatal: Remote branch 1.7.0 not found in upstream origin

with 
platform_packages = framework-arduinocubecell@https://github.com/HelTecAutomation/CubeCell-Arduino.git#V1.7.0
i get the same error as above.

**Comment by jezdd** [comment]
No idea if its related, I am using a different board.

```
[env:cubecell_node]
platform = heltec-cubecell
platform_packages = framework-arduinocubecell@https://github.com/HelTecAutomation/CubeCell-Arduino@1.7.0
board = cubecell_node   

```
Worth testing to see if it compiles with you (obviously it not same board as yours)

```
Processing cubecell_node (platform: heltec-cubecell; board: cubecell_node; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/heltec-cubecell/cubecell_node.html
PLATFORM: Heltec CubeCell (1.1.0) > Heltec CubeCell-1/2AA Node (HTCC-AB02A)
HARDWARE: ASR6502 48MHz, 16KB RAM, 128KB Flash
PACKAGES: 
 - framework-arduinocubecell @ 1.7.0+sha.d9402fe 
 - tool-cubecellelftool @ 0.0.1 
 - toolchain-gccarmnoneeabi @ 1.90201.191206 (9.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep, Compatibility ~ soft
Found 15 compatible libraries
Scanning dependencies...
Dependency Graph
|-- LoRa @ 1.0
|-- SparkFun HTU21D Humidity and Temperature Sensor Breakout @ 1.1.3
|-- Sensor - Heltec Produced @ 1.0
Building in release mode
Checking size .pio\build\cubecell_node\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [====      ]  36.4% (used 5960 bytes from 16384 bytes)
Flash: [=======   ]  68.6% (used 89904 bytes from 131072 bytes)
=============================================== [SUCCESS] Took 2.76 seconds ===============================================

```

**Comment by eikaramba** [comment]
not really, but i think this is because i have a dependency on the RGB.
CONFIGURATION: https://docs.platformio.org/page/boards/heltec-cubecell/cubecell_node.html
PLATFORM: Heltec CubeCell (1.1.0) > Heltec CubeCell-1/2AA Node (HTCC-AB02A)
HARDWARE: ASR6502 48MHz, 16KB RAM, 128KB Flash
PACKAGES:
 - framework-arduinocubecell @ 1.7.0+sha.d9402fe
 - tool-cubecellelftool @ 0.0.1
 - toolchain-gccarmnoneeabi @ 1.90201.191206 (9.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 18 compatible libraries
Scanning dependencies...
Dependency Graph
|-- RGB @ 1.0
|-- LoRa @ 1.0
|-- EEPROM @ 1.0
Building in release mode
Compiling .pio\build\cubecell_board\src\main.cpp.o
Compiling .pio\build\cubecell_board\lib74a\RGB\CubeCell_NeoPixel.cpp.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\LoRaMac.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\LoRaMacClassB.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\LoRaMacConfirmQueue.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\LoRaMacCrypto.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\Region.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionAS923.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionAU915.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionCN470.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionCN779.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionCommon.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionEU433.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionEU868.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionIN865.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionKR920.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionUS915-Hybrid.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\loramac\region\RegionUS915.c.o
Compiling .pio\build\cubecell_board\lib3a8\LoraWan102\radio\radio.c.o
Compiling .pio\build\cubecell_board\libac8\DISPLAY\HT_Display.cpp.o
Compiling .pio\build\cubecell_board\libac8\DISPLAY\HT_DisplayUi.cpp.o
Compiling .pio\build\cubecell_board\libac8\DISPLAY\HT_st7735.cpp.o
Compiling .pio\build\cubecell_board\libac8\DISPLAY\HT_st7735_fonts.cpp.o
Compiling .pio\build\cubecell_board\lib820\LoRa\LoRaWan_APP.cpp.o
Compiling .pio\build\cubecell_board\lib820\LoRa\LoRa_APP.cpp.o
Compiling .pio\build\cubecell_board\lib439\EEPROM\AT24C32N.cpp.o
Compiling .pio\build\cubecell_board\lib439\EEPROM\EEPROM.cpp.o
Archiving .pio\build\cubecell_board\libFrameworkArduinoVariant.a
Compiling .pio\build\cubecell_board\FrameworkArduino\SPI\SPI.cpp.o
Compiling .pio\build\cubecell_board\FrameworkArduino\Serial\HardwareSerial.cpp.o
Compiling .pio\build\cubecell_board\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\cubecell_board\FrameworkArduino\Wire\Wire.cpp.o
src\main.cpp:10:33: error: 'RGB' was not declared in this scope
   10 | extern CubeCell_NeoPixel led(1, RGB, NEO_GRB + NEO_KHZ800);
      |                                 ^~~
*** [.pio\build\cubecell_board\src\main.cpp.o] Error 1
Indexing .pio\build\cubecell_board\libFrameworkArduinoVariant.a
C:\Users\eike\.platformio\packages\framework-arduinocubecell\libraries\LoRa\src\LoRaWan_APP.cpp:6:29: error: 'RGB' was not declared in this scope
    6 | CubeCell_NeoPixel pixels(1, RGB, NEO_GRB + NEO_KHZ800);
      |                             ^~~
*** [.pio\build\cubecell_board\lib820\LoRa\LoRaWan_APP.cpp.o] Error 1

**Comment by jezdd** [comment]
Try board_build.arduino.lorawan.rgb = DEACTIVE

Are you sure your board supports RGB led?

I suspect it does not, RGB would be defined in the board definitions

**Comment by eikaramba** [comment]
yes the cubecell board has a led in the middle ;) https://heltec.org/project/htcc-ab01-v2/
i unfortunately also need it to output some kind of visual debug information. but i will try to see if i can make 1.7.1 work somehow or need to wait for heltec to upgrade the dependency maybe

**Comment by jezdd** [comment]
Could try #define RGB P0_7 //gpio4
